### ISSUE TITLE
Keefox still phones home to "anonymousstats.keefox.org" even though it has been disabled

### ISSUE THREAD

**Issue by BlueMax** [luckyrat/KeeFox#566] opened 2015-10-19 23:02 UTC
Keefox tries every 15 seconds to resolve "anonymousstats.keefox.org" even though that option has been disabled in options and it is bypassing windows standard DNS resolving.

Keefox 1.5.3
Win7
Firefox 41.0.2

**Comment by luckyrat** [comment] 2015-10-20 07:13
That's expected behaviour as per the privacy policy and more detailed manual page here: https://github.com/luckyrat/KeeFox/wiki/en-%7C-Metrics-collection

If it's bypassing standard windows resolving that'll be down to something Firefox have changed since my initial tests but there would be nothing KeeFox can do to alter that behaviour.

**Closed by luckyrat** 2015-10-20 07:13 UTC

**Comment by BlueMax** [comment] 2015-10-20 09:14
To be more precise... It doesn't send any data. It just resolves the address over and over again (DNS). This doesn't make any sense and just hammers the DNS server.

**Comment by frijsdijk** [comment] 2017-03-07 06:41
Confirmed here as well (noted on a pi-hole)

**Comment by bcutter** [comment] 2017-04-16 00:50
Copy & paste frijsdijk´s post.
