### ISSUE TITLE
HTTP Basic Auth since update to Firefox 50

### ISSUE THREAD

**Issue by BigBoppa** [luckyrat/KeeFox#730] opened 2016-11-18 12:33 UTC
since the update to firefox 50 HTTP Basic Auth doesn't work any longer with keefox 1.6.3

**Comment by dlech** [comment] 2016-11-18 16:15
Duplicate of #709.

**Closed by dlech** 2016-11-18 16:15 UTC
Labels: duplicate

**Comment by BigBoppa** [comment] 2016-11-18 16:19
noop, this issue is about the actual release Firefox 50, not about the beta as described in #709
