### ISSUE TITLE
Add option to remove "generate password" from right click menu

### ISSUE THREAD

**Issue by ceribik** [luckyrat/KeeFox#636] opened 2016-03-11 21:29 UTC
On linux, using the generate password option causes the entire system to hang for 5-10 secs. I have replicated this on two separate systems.

It would be nice to have an option that disables this function from the FF right click menu so it cannot be accidentally clicked.

**Comment by luckyrat** [comment] 2016-03-14 13:17
This is a duplicate of #381 but also potentially relates to #391 - maybe that will help you resolve the problem with the generate password option on your systems or maybe you'll be able to provide some more information that can help us to narrow down the faulty component.

**Closed by luckyrat** 2016-03-14 13:17 UTC
