### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by Floflr** [luckyrat/KeeFox#654] opened 2016-04-14 16:31 UTC
Hello,
When I use the dark theme on the keefox linux interface is unreadable.
I tested with several theme.
![bug keefox](https://cloud.githubusercontent.com/assets/18467487/14535573/b9fb25cc-026e-11e6-9402-fb53ebdb0bb4.png)
I'm using Firefox 45.0.1 on Manjaro, with KeeFox 1.6.0 from addons.mozilla.org.

**Comment by luckyrat** [comment] 2016-04-25 20:35
Looks like a duplicate of #281

**Closed by luckyrat** 2016-04-25 20:35 UTC

**Comment by Floflr** [comment] 2016-04-29 18:49
Yes it's a double, sorry.
But did you find a solution to correct the problem because I am not a developer and use the NoXPhasma's solution #281 seems complicated for me.
Thank you for all the work you do.
