### ISSUE TITLE
Something is broken since 1.5.3

### ISSUE THREAD

**Issue by DominikStyp** [luckyrat/KeeFox#539] opened 2015-09-15 01:57 UTC
Previous version (1.4) works great, but last (from 1.5) has a bug which uses whole thread of my processor with no reason. Please fix that.

**Comment by luckyrat** [comment] 2015-09-15 06:44
They are identical except for a few changes to text strings and the addition of the French language. Unless you are using an affected language this can't be caused by the upgrade to KeeFox (and even then it would be a Firefox bug if slightly different text can cause high CPU usage).

If you can reliably reproduce the issue after swapping back and forth between the two versions a few times, please report it as a Firefox bug. The only possible explanation that comes to mind is if their new addon signing process triggers a bug but even that seems incredibly unlikely so I would suggest looking for other reasons for this high CPU usage.

**Comment by ilneroviaggiatore** [comment] 2015-09-15 10:02
HI, same issue.
After upgrade to 1.5.3, very high CPU usage.

Thanks!

**Comment by ilneroviaggiatore** [comment] 2015-09-15 14:52
Hi, i downgraded to 1.5.3 b1 and usage CPU is again correct and KeeFox work fine again for site where it usually worked fine for me.

**Comment by luckyrat** [comment] 2015-09-15 16:45
Which site?

**Comment by ilneroviaggiatore** [comment] 2015-09-15 17:00
Hi, site are private tracker forum as http://www.bit-italia.org.
But now also 1.5.3 b1, as newer one, has high CPU usage. I have again to remove KeeFox from extensions.
I hope the problem will be resolved!
Thanks!

**Comment by luckyrat** [comment] 2015-09-15 19:15
I can't reproduce this, which is unsurprising since none of our 500 beta testers reported the problem so it must be pretty rare.

Those of you experiencing the problem will have to supply a lot more detail about the steps that you take to trigger the problem and information about your computer (O/S version, all other security software, Firefox addons, KeePass plugins, etc.). Hopefully that will then reveal some common cause of the problem.

**Comment by Warlockbugs** [comment] 2015-09-16 06:19
Same issue.
I also had problems with upgrading from 1.4.x to 1.5.x. It couldn't connect to my KP until i did both: i've upgraded KP2 to 2.30 and uninstalled Keefox, then installed Keefox again.
The CPU usage goes sky high as soon as FF opens a new URL and then goes down when the page is fully loaded. But hey, at least, i've got it to work with my KP2.

FF Developer Edition x64, 42.0a2, 2015-09-15, Windows 10 x64, KeePass 2.30 portable.

**Comment by Warlockbugs** [comment] 2015-09-16 06:21
Also, i forgot to add, e10s is enabled.

**Comment by DominikStyp** [comment] 2015-09-16 06:52
Hi!
Sorry, I was mistaken about downgrade version, now I see that problem disappeared after downgrade to last 1.4 version (1.4.8.1-signed), with all 1.5.x versions high processor usage persists.
It doesn't matter which site I have opened in Firefox, because after browser start CPU goes to 15% (full 1 thread usage).

**Comment by ilneroviaggiatore** [comment] 2015-09-16 08:54
Hi, problem there is even if before remove all of addons and then install only new KeeFox.
From yesterday even after downgrade there is same problem of high cpu usage.
My system:
Windows XP SP3
Java 7.80 (build 1.7.0_80-b15)
Avast Free Antivirus 10.3.2225

Thanks for the support!

**Comment by general714** [comment] 2015-09-16 12:12
Just to say, I have the exact same issue. I reckon that it's very common as I've had it on two different computers with different set-ups. Downgraded to 1.4.8.1 signed and it's back to usual. This is a GREAT add-on and works extremely well, but the new version maxes out CPU and therefore needs tweaking urgently. 
Windows 7 x64, Firefox 40.0.03

**Comment by ilneroviaggiatore** [comment] 2015-09-17 12:46
Downgraded to 1.4.8 and it works fine.

**Comment by dharkbizkit** [comment] 2015-09-18 12:33
Same problem. cpu usage instantly goes up to 32% the moment i start FF with KF and my ram starts to fill up, untill FF reaches 1gb. the longer i use the browser in that condition. the slower it get. after 1h keyboard imput takes 5 seconds to appear on the screen. 
problem apperently appeared over night, not directly after the update a few few days ago
FF 40.0.3
(addons - anonymoX, ask for sanitize,disconnected,download status bar, down em all, ghostery,https everwhere,random agent spoofer, secure snaitize,uBlock, youbetube video and audio downloader)
win 10 x64
avira
Kp2 auto backup

some screens 

![without](https://cloud.githubusercontent.com/assets/14347201/9959190/15845e38-5e12-11e5-9448-8da4a97714f8.jpg) FF after starting without KF

**Comment by akava** [comment] 2015-09-18 13:25
Same on my PC. Downgraded to 1.4.8 which fixed the CPU consumption
https://github.com/luckyrat/KeeFox/releases/tag/v1.4.8

**Comment by Etuldan** [comment] 2015-09-18 21:59
Same as @akava , high CPU usage with current version, downgrade is OK.
I use French locales on my computer (OS & Firefox)
Win7 64.

**Comment by bege10** [comment] 2015-09-20 13:36
CPU usage over 50% with KeeFox 1.5.3, even with only one empty tab, normal with v1.4.8

Windows 7 Professional 64 bit SP1 (German)
Firefox 40.0.3 (German)
Security programs: Windows firewall, 360 Total Security (anti-virus)

**Comment by luckyrat** [comment] 2015-09-21 12:32
When you see the high CPU usage, is KeeFox connected to KeePass? E.g. can you search the KeeFox main panel for results from KeePass?

**Comment by Etuldan** [comment] 2015-09-21 12:37
KeeFox is connected to KeePass when there is High CPU usage. (I didn't try the search, but the autocompletion of fields was ON (without "autotype", ofc))

**Comment by Preveder** [comment] 2015-09-21 14:45
Unfortunately, i've seen high usage even when my Keefox [had issues with connecting to KeePass 2](https://github.com/luckyrat/KeeFox/issues/539#issuecomment-140641610). I can't reproduce these issues anymore, unfortunately.
The CPU usage goes high as soon, as a new tab or page is loaded, and the website is referenced in one of the entries in KeePass 2 database. On github in particular, when i open "sign in" page, firefox nearly hangs for about 5-10 seconds, before rendering the page. The keefox icon goes from blue to gray (as if it was disconnected from keepass) for a mere fraction of second before changing to blue-plus icon (i.e. matched entries found for the website).
On a cold start, firefox shows standard "script takes too long to execute" notice on the last open webpage (i.e. when loading previous session).

**Comment by Warlockbugs** [comment] 2015-09-21 15:02
Unfortunately, i've seen high usage even when my Keefox had issues with connecting to KeePass 2. I can't reproduce these issues anymore.
The CPU usage goes high as soon, as a new tab or page is loaded, and the website is referenced in one of the entries in KeePass 2 database. On github in particular, when i open "sign in" page, firefox nearly hangs for about 5-10 seconds, before rendering the page. The keefox icon goes from blue to gray (as if it was disconnected from keepass) for a mere fraction of second before changing to blue-plus icon (i.e. matched entries found for the website).
On a cold start, firefox shows standard "script takes too long to execute" notice on the last open webpage (i.e. when loading previous session).

**Comment by luckyrat** [comment] 2015-09-21 19:22
Does it indicate which "script takes too long to execute"?

**Comment by Warlockbugs** [comment] 2015-09-21 19:48
No, clicking "debug" does nothing. I think its glitched. I'll try my best to get as much more info as possible next time i see this pop-up notice.

**Comment by ilneroviaggiatore** [comment] 2015-09-21 22:07
Yes, when i see the high CPU usage, KeeFox is connected to KeePass.

**Comment by bege10** [comment] 2015-09-22 09:02
Here it doesn't matter whether KeeFox is connected to KeePass or not. As soon as Firefox is started I have the high CPU usage with KeeFox 1.5.3 (see my post above)

Windows 7 Professional 64 bit SP1 (German)
Firefox 40.0.3 (German)
Security programs: Windows firewall, 360 Total Security (anti-virus)

**Comment by luckyrat** [comment] 2015-09-23 19:02
I'm afraid I still can't see anything wrong, nor any clear pattern from the information supplied so far.

Can someone experiencing the problem please create a completely new Firefox profile, leave all settings at their defaults and ensure every plugin (e.g. flash, java, antivirus, etc.) is disabled and then install KeeFox to see if the problem occurs again?

**Comment by Warlockbugs** [comment] 2015-09-24 20:17
I've been trying to catch which script stalls the FF, but without any luck. It doesn't point to any script or targets random scripts without any specific pattern,

**Comment by Warlockbugs** [comment] 2015-09-24 20:36
Update: I don't have any CPU usage issues on a fresh profile in Firefox Developer Edition 42 with Keefox as the only installed addon. I do receive strange message when linking to KeePass:
"This version of Keefox (1.4.4) is older than the installed KeePassRPC plugin (1.5.3)."
Both KeePass and Keefox are up-to-date, obviously.
I'll try to perform a full profile wipe and reconfigure all addons from the ground up (this will take ages :( ) on weekend.

**Comment by Warlockbugs** [comment] 2015-09-24 21:13
I beg your pardon for notification spam, but i've got another update:
Disabling e10s on the old profile has the same effect as creating a new profile (where e10s was probably disabled by default). The issue lies somewhere within e10s compatibility.

**Comment by luckyrat** [comment] 2015-09-28 20:06
Does everyone with this problem have e10s enabled?

I do too so it's not incompatible but maybe there is an e10s related Firefox bug on some hardware platforms?

> "This version of Keefox (1.4.4) is older than the installed KeePassRPC plugin (1.5.3)."

This only gets displayed when you have an old version of KeeFox installed but if you have session restore enabled I think it's possible for the old information to be displayed after you restart Firefox. It will go away once you close the tab (unless you really do have an old version of KeeFox installed).

**Comment by bcutter** [comment] 2015-10-09 09:40
Same here on Win7 x64 with KF v1.5.3. firefox.exe consumes appr. 13-14 % (on a 8 core cpu). Took a time to track it down to KeeFox, but it´s definitely KF. Disabled addon. Problem gone. Enabled again. High CPU usage back. Doesn´t matter if KP is running and/or if KF is connected to KP; as soon FF is running KF is consuming the CPU usage.

KF v1.5.3
KP v2.30
KPRPC v1.5.3

Please keep working on this and provide a fix! It´s really horrible to use FF this way.

**Comment by luckyrat** [comment] 2015-10-09 12:37
> Please keep working on this and provide a fix! It´s really horrible to use FF this way.

If I discover that this is a problem with KeeFox I will definitely treat it as the top priority for a fix. However, as I explained above, I am currently not able to work on this since the problem affects only a small number of computers so all I can offer is a keen eye on this issue in case I spot any patterns regarding particular configurations or 3rd party software - unfortunately most people's comments do not contain enough information to make this possible.

Downgrading is obviously a good option for the time being but it is only a matter of weeks or months before those earlier KeeFox versions stop working with the latest Firefox version so I would prefer to have identified the cause of the problem before you are all forced to upgrade again. Since the problem is unlikely to be with KeeFox itself, it is even more important to work out the cause quickly so that Mozilla or other involved 3rd parties have enough time to fix it.

**Comment by bcutter** [comment] 2015-10-09 12:45
>unfortunately most people's comments do not contain enough information to make this possible.

How can I / can we help? What information do you need in detail?

**Comment by luckyrat** [comment] 2015-10-10 16:42
From my earlier but disparate comments:

Those of you experiencing the problem will have to supply a lot more detail about the steps that you take to trigger the problem and information about your computer (O/S version, all other security software, Firefox addons, KeePass plugins, etc.). Hopefully that will then reveal some common cause of the problem.

Does everyone with this problem have e10s enabled?

Can someone experiencing the problem please create a completely new Firefox profile, leave all settings at their defaults and ensure every plugin (e.g. flash, java, antivirus, etc.) is disabled and then install KeeFox to see if the problem occurs again?

Essentially we're looking for any Firefox configuration setting, 3rd party software, operating system configuration or hardware that is common for those people that experience the problem.

PS: Mozilla have now confirmed that KeeFox 1.4.x will definitely no longer work in Firefox 44 onwards (due out in January 2016).

**Comment by ymym** [comment] 2015-10-11 18:26
I started using keepass 2.30 portable today and installed keefox 1.5.3
I really like this addon but yes, it uses 30% of my CPU which makes using it too hard.

Win7 x64, FF 40.0.3, Outpost security suite pro 9.1

My system language is russian, keepass russian too. I thought that maybe a problem and switched keepass to english but it not helped.

What i did from the beginning: 
install keepass, make my database etc.
import passwords from FF with keepass plugin "firefox importer"
install keefox and make tutorial
connect keefox to keepass and try to use it on couple sites and here i noticed bit CPU usage.
then i found this thread and downgraded keefox to 1.4.8  as guys said here but it can't connect to keepass:  when i open a site with forms theres a message from FF that my password base is not opened, i click "open keepass" button in this window and keepass just brings to the front, no connection and nothing happens.

I hope this will help you to understand what's wrong.

**Comment by dot-nom** [comment] 2015-10-13 06:17
Hi
This problem seems to interfere it with other Addon.
I installed Win7x64(Japanese) on VMware and tried it on a completely new Firefox profile.
CPU utilization rose when I installed only A and B.
A=KeeFox   1.5.3
B=AnonymoX 2.5.2
In the case of the version that is old in either one, CPU useage is not rise up.
C=KeeFox   1.4.8.1
D=AnonymoX 2.4.6.1
So now I use of A & D in combination it.

**Comment by luckyrat** [comment] 2015-10-13 06:36
So here's another question for everyone affected: Do you use a proxy server (or an add-on like AnonymoX which enables a proxy server on your behalf)?

**Comment by dot-nom** [comment] 2015-10-13 06:54
I do not introduce the proxy-related thing at all any place other than AnonymoX.

**Comment by xion87** [comment] 2015-10-13 11:02
got the same issue, on windows xp, keefox make firefox use 100% cpu on my windows 7 no issue..

**Comment by luckyrat** [comment] 2015-10-13 22:24
Not sure about everyone else's situation, but it looks like AnonymoX is at fault for @dot-nom 

I don't know exactly what it's doing but inspecting what slows down Firefox when it's installed points squarely at its code (jquery in particular) and I can't see any indication of KeeFox being involved. That KeeFox is implicated by being installed too indicates that the addon is doing something very slow with every network request made through your browser (even when the add-on is disabled it is not cleaned up until after a Firefox restart which is a big red flag for me). The warnings of adverts being injected into pages is a pointer towards the cause of the problem (maybe it does something slow every time just to try to work out whether it should insert an advert and the exceptionally slow performance every few seconds might be it trying to inject an advert to KeeFox's communication with KeePass?)

I reiterate that everyone experiencing potential performance problems with KeeFox should triple check that there is no malware or otherwise network-interfering software installed on your machine - I'm sure it's not the only possible cause of the problems and I'm not sure why the upgrade to v1.5 would change the behaviour but it's definitely a possibility worth checking carefully.

**Comment by ymym** [comment] 2015-10-14 08:01
i checked my system with antivirus and antimalware softwares and nothing was found.

Keefox updated today from 1.4.8 to 1.5.3 without any requests and started to use 30% of my CPU. 

It's not cool, how can i make it unupdatable? I don't need 1.5.3 if it slows down my PC, i want 1.4.8 ))

**Comment by luckyrat** [comment] 2015-10-14 20:48
Since I'm suspicious that there are malfunctioning proxies involved somewhere, please can someone with the problem provide a KeeFox Debug log of a roughly 10 second period where the problem is occurring? That might confirm (or reject) a theory that a malicious or faulty proxy is constantly forcing KeeFox to attempt reconnection to KeePass faster than it normally would. It still doesn't quite add up but since connection establishment is the only significant bit of CPU heavy work KeeFox does and there are implications above that a proxy might be involved, it at least warrants gathering some further data.

**Comment by luckyrat** [comment] 2015-10-14 21:08
> how can i make it unupdatable?

You should be able to do that in the Firefox add-ons config screen (click the "more" link to find the Firefox option specific to updating KeeFox).

> I don't need 1.5.3

As I said a couple of posts earlier, this might be true but only for a short time. Firefox 44 will definitely not work with versions earlier than 1.5.3 (so January is a definite cut-off point but of course Mozilla might do something to break 1.4.8 before then so there are no guarantees you'll even get those 3 months of use)

**Comment by akava** [comment] 2015-10-15 05:42
No proxy installed in my FF. CPU consumption is high no matter if KeePass unlocked or not.
Collected DEBUG logs for 40 secs or so. Will send it privately.
We can catch up by Skype to debug the problem

**Comment by luckyrat** [comment] 2015-10-15 07:22
Thanks @akava. I've looked at the log and don't see the behaviour I was interested in seeing (continuous attempts to reconnect to KeePass or large-scale repeated data transfer with KeePass). In fact, there is nothing immediately unusual about your log except for the large periods of time between some log statements `Deleting any references to login data for recently completed async find logins call.` seems to precede at least 10 seconds of nothing happening. This might be perfectly normal behaviour based upon your interaction with the browser and KeePass or it might indicate that Firefox was too busy during that period to actually allow KeeFox to do anything. I'll try to investigate that in more detail at the weekend.

In the mean-time, I'm wondering if you would be able and willing to provide a performance log from Firefox for me to analyse? I think it would require running Firefox Nightly or at least Firefox Developer Edition. I'm going to test out the process of sharing this performance data today before writing up instructions on how to do it.

**Comment by akava** [comment] 2015-10-15 09:39
>it might indicate that Firefox was too busy during that period
No, FF was not busy. I was clicking around the page.

> if you would be able and willing to provide a performance log from Firefox for me to analyse
sure, if you tell me how to do that and how to collect the logs

**Comment by luckyrat** [comment] 2015-10-15 19:57
> sure, if you tell me how to do that and how to collect the logs

1. Open the Browser Toolbox by following the instructions described here: https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox
2. Then go to the Performance tab
3. Click "Start Recording"
4. Wait 30 seconds (try to avoid doing anything else in Firefox at the same time)
5. Click "Stop Recording"
6. On the left there will be a "Recording #1" section
7. Click the "Save" link in that box and put the "profile.json" file somewhere.

It should be small enough to email but feel free to post elsewhere for me to download if you prefer.

Thanks!

**Comment by ymym** [comment] 2015-10-16 18:45
maybe we can connect on skype and you will see what's wrong and why CPU usage is so high?

**Comment by luckyrat** [comment] 2015-10-17 11:18
@akava It looks like the cause of your slow Firefox is a Youtube download add-on. As you can see from the reviews, it attracts similar criticism as AnonymoX in terms of intercepting network requests in order to occasionally insert advertising: https://addons.mozilla.org/en-GB/firefox/addon/1-click-youtube-video-downl/reviews/

The failure mode appears to be identical to AnonymoX in that both add-ons include the jQuery Javascript library and both get stuck in some kind of loop causing jQuery's timer functionality to run out of control.

I'm still not sure what might have changed in KeeFox 1.5 to trigger the bugs in these other add-ons but uninstalling the faulty add-on should make Firefox performance go back to normal. Let me know if not, just in case there is more than one problem contributing to the high CPU usage.

**Comment by xion87** [comment] 2015-10-17 11:31
I confirm that i unistalled that plugin  and upgraded keepfox, now it 
work fine!

Il 17/10/2015 13.18, Chris Tomlinson ha scritto:

**Comment by luckyrat** [comment] 2015-10-17 11:41
Please can anyone still experiencing this problem follow the instructions above to get a performance log. I'm particularly interested to get logs from those who have seen this problem despite having no other add-ons installed.

The log could contain URLs of website's you have opened in your current session so I recommend zipping it up (compressing) and sending it to me privately (put my username in front of an `@` and `musites.com`).

Thanks for the offers of Skype debugging but I don't have Skype at the moment and think that any debugging would be pretty aimless and time-consuming for both of us given the current information available (that might change of course). CC: @ymym 

PS: Glad to hear it @xion87 :-)

**Comment by Warlockbugs** [comment] 2015-10-18 04:08
@luckyrat 
Thanks for pointing towards the potential source of the problem! I've browsed through my addons in search for JS-related addons and found another culprit:
https://addons.mozilla.org/en-us/firefox/addon/canvasblocker/
I've disabled it and now it works fine in e10s mode again.
Strangely enough, this performance issue only pops up in e10s mode, so disabling e10s may be a suitable temporary alternative to uninstalling/disabling addons.

**Comment by akava** [comment] 2015-10-18 17:46
@luckyrat Disabling the video downloaded did it. Thanks!

**Comment by ymym** [comment] 2015-10-19 15:45
i tried turning off couple addons and see CPU usage.
Disabling  FoxyScrobbler  makes firefox work with keefox properly, CPU usage is low.  
Don't need foxyscrobbler anymore, keefox is better))

**Comment by bcutter** [comment] 2015-10-22 17:14
>So here's another question for everyone affected: Do you use a proxy server (or an add-on like AnonymoX which enables a proxy server on your behalf)?

I have ProxMate and ProxTube addons installed and activated.

Do you need some other user input?

**Comment by luckyrat** [comment] 2015-10-22 21:36
@bcutter well the first thing to try would be seeing if the high CPU usage goes away when you disable one and/or both of those addons (do a full Firefox restart even if they claim to be restartless addons).

**Comment by bcutter** [comment] 2015-10-24 16:43
@luckyrat Disabled both of them (separately and together) - nothing changed with up to date KF v1.5.3 (= again high cpu usage). Also disabled a bunch of other addons - still high cpu usage.

For me it seems the proxy guess doesn´t point to the right direction.

Downgraded again to v1.4.8 !!!!!!!!!!!!!!

**Comment by luckyrat** [comment] 2015-10-25 13:08
OK @bcutter so maybe you could provide me with a performance profile as I described above? Then I can take a look into it to try to find out what's happening on your machine.

**Comment by ymym** [comment] 2015-11-18 09:29
i installed anonymoX  and FF uses 30% CPU again.

can you please fix it somehow cause i really need both anonymox and keefox?

**Comment by luckyrat** [comment] 2015-11-18 12:02
Unfortunately it's not something I can fix; it's either a bug with anonymox or with Firefox. The notable culprit in all cases is the jQuery Javascript library but I'm not in a position to be able to say whether the bug lies in that library, Firefox or the usage patterns of the affected addons like anonymox.

Those add-on authors might be able to shed more light on the problem but I'm afraid it looks like a pretty complex bug so I wouldn't hold out much hope of a speedy resolution, although we could get lucky if they find that upgrading the version of jQuery they use magically fixes it.

**Comment by bege10** [comment] 2015-11-20 17:20
Thank you for your help, luckyrat, here the add-on PassSec+ is incompatible with KeeFox (or the other way round ;-)  )

**Comment by general714** [comment] 2015-11-21 11:07
Clearly there are a large number of Add-ons that cause this problem with Keepass, so it's no good blaming everyone else. This essential add-on needs to be sorted out. I've checked with the tech folk at anonymoX who say, "we only seem to have this problem with Keepass and I personally doubt that this problem will have an easy explanation. In most cases such problems are (historically) triggered by an combination of Firefox bugs, anonymoX race conditions and problems with the other add-on.
Therefore I unfortunately can't tell you when we will find a solution to this problem."

Hope this can be sorted before we can no longer use the older, working version of Keepass.

**Comment by bcutter** [comment] 2015-12-16 18:55
Any news? Time´s counting! :(

**Comment by luckyrat** [comment] 2015-12-17 07:57
@bcutter: I'm awaiting your performance profile so I can help you work out which add-on is causing your problem. Beyond that, it is looking increasingly unlikely that this performance problem is caused by KeeFox but if your profile indicates a new category of problem I will of course look into it.

My intention is to close this ticket as invalid in January unless any actual evidence of a problem with KeeFox emerges before then.

**Comment by bcutter** [comment] 2015-12-20 16:53
You´ve got mail Sir.

**Comment by luckyrat** [comment] 2015-12-20 17:32
@bcutter: Message received.

You have the PassSec+ addon installed and that is causing the problem (same pattern as the other faulty add-ons - it looks like a Firefox bug being triggered by the use of the jquery library, possibly only when also in the presence of certain e10s compatible addons such as KeeFox).

**Comment by bcutter** [comment] 2015-12-20 17:40
I disabled PassSec+, updated KeeFox to v1.5.4, connected to KP DB and watched CPU usage: All fine. Happy to be ready for January.

For the moment I can and will live with that (KeeFox is > important than PassSec+); I´ll try to contact the developer(s) of PassSec+. By the way: KeeFox is a signed extension, PassSec+ isn´t at the moment... :)

So I agree: KeeFox at least isn´t the source of this bug, so it´s pretty innocent.

**Comment by luckyrat** [comment] 2016-01-09 20:13
I came across a comment the other day which implied there are (sometimes multiple) instances of common javascript libraries bundled with Firefox itself. If one of those is (or conflicts with) the version of jQuery being used by the addons mentioned in this issue, that might be a worthwhile avenue for investigation for the addon authors.

**Closed by luckyrat** 2016-01-09 20:13 UTC
Labels: need info
