### ISSUE TITLE
new Google account sign-in

### ISSUE THREAD

**Issue by androidland** [luckyrat/KeeFox#447] opened 2015-05-18 07:25 UTC
please make support for new google account sign in.
https://productforums.google.com/forum/m/#!category-topic/gmail/oAsE-6wmaSU

**Comment by luckyrat** [comment] 2015-05-21 21:49
Presumably I don't see this because I have Google Apps. Maybe it will be released for me later but from what I understand, this is now just a multi-page login so what specific new feature are you looking for KeeFox to support?

I'm tracking this for v1.5 in case we can get some more feedback during beta testing about whether 1.5 works with this updated login process (regardless of whether it works in 1.4.x).

**Comment by PieterBreugelmans** [comment] 2015-08-08 09:22
Some reference(s):
Bug 849540 - Log in to Gmail (IMAP/SMTP) using OAuth in backend 
https://support.mozilla.org/en-US/questions/1075788

The OAuth2 authentication opens up a web browser dialog window to https://accounts.google.com/ServiceLogin?passive=..... 

Source code:
https://dxr.mozilla.org/comm-central/source/mailnews/base/src/msgOAuth2Module.js?offset=1300#84

The request is for KeeFox to be able capture the username and password on this popup window.

**Comment by luckyrat** [comment] 2015-08-08 09:36
So it sounds like this might be a Thunderbird related request?

Are you both using KeeFox 1.5? Which version of Thunderbird/Firefox?

Maybe @dlech can make sense of it but as it stands I do not understand what the problem is or what the desired behaviour is. As I said before, KeeFox 1.5 works perfectly for me with Google logins, but maybe it's something I'd only see if I used Thunderbird.

**Comment by PieterBreugelmans** [comment] 2015-08-08 11:07
I was under the impression that  @androidland was talking about the new OAuth2 in Thunderbird for Gmail but I was wrong about that. Apologies for that.

My issue is specific to Thunderbird with keefox-1.4.8-tb+fx-windows.xpi so I've gone ahead and installed keefox-1.5.3b5-tb+fx.xpi from file and that does indeed improve things a lot. I'll open a new issue if I'm still seeing issues.

**Comment by luckyrat** [comment] 2015-08-15 16:16
OK, so it looks like this is a non-issue. Please open a new issue with clear details of the problem if you think something is still broken.

**Closed by luckyrat** 2015-08-15 16:16 UTC
