### ISSUE TITLE
KeeFox integration with Thunderbird 45.2.0 not working in 1.6.3 or 1.6.3b1

### ISSUE THREAD

**Issue by tiboroche** [luckyrat/KeeFox#699] opened 2016-08-26 08:46 UTC
Hey all,

I am currently using KeeFox 1.6.1b1 on Ubuntu on Thunderbird and it is working fine. But when I tried to upgrade the plugin to 1.6.3 or 1.6.3b1, it is not working anymore. Do you have any idea why it is not working anymore ? Can I check some things in the logs to help me diagnose this issue ? 

After each upgrade, I copy the KeePassRPC.plgx to the keepass plugin to update it. 

Thanks for your help.

* Ubuntu version : 16.01
* Thunderbird version : 45.2.0
* Keepass version : 2.32 (Dev)
* KeeFox version : 1.6.1b1 (working well)

**Comment by dlech** [comment] 2016-10-29 02:59
What exactly is not working? Screenshots showing the difference are helpful. Is there anything useful in the error log? Does anything on the [troubleshooting wiki page](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Troubleshooting) look useful?

**Comment by dlech** [comment] 2016-10-29 03:02
Looks like this is a duplicate of #684. Please comment there.

**Closed by dlech** 2016-10-29 03:02 UTC
