### ISSUE TITLE
"Install Keepass" pops up on every start

### ISSUE THREAD

**Issue by boldt** [luckyrat/KeeFox#493] opened 2015-06-17 16:12 UTC
My System:

* Ubuntu 14.04.1 LTS
* Mono 3.2.8
* KeePass 2.29

Issue:

Every time I start my Firefox, the "Install KeePass" page is loaded:

* chrome://keefox/content/install_mono.xul

Even if this page is loaded, KeeFox works as expected. The Button in the toolbar works well and my passwords are entered automatically.

**Comment by dlech** [comment] 2015-06-17 17:25
Duplicate of #471. Please see if any info there is useful and comment on that issue if you have any further information.

**Closed by dlech** 2015-06-17 17:25 UTC
Labels: duplicate
