### ISSUE TITLE
Uninstalling keefox from Thunderbird

### ISSUE THREAD

**Issue by tinne** [luckyrat/KeeFox#446] opened 2015-05-17 10:57 UTC
When uninstalling keefox from Thunderbird, password saving in the embedded Thunderbird password manager is not re-enabled, and I find it never documented how to enable this feature manually.

Thus, after trying thunderbird (with loads of mailboxes, so that I do not easily dare setting up a new profile), all new passwords since must be manually entered on startup.

Please provide me with the necessary information to fix my setup and clean up the add-in uninstallation routine to fix this on removal. Yes, I read that I have to remove every single pass before installation from the faq in the meantime, but this is not checked, and so it does not help.

**Comment by dlech** [comment] 2015-05-17 19:10
Duplicate of #389.

From that issue, it looks like you can fix the problem by going to the Advance tab in Preferences and selecting "Config Editor...". Search for "rememberSignons". It should find ""signon.rememberSignons".  Right-click on that and reset it back to the default value (true).

**Comment by dlech** [comment] 2015-05-17 19:10
Any further discussion should be done on #389.

**Closed by dlech** 2015-05-17 19:10 UTC
Labels: duplicate
