### ISSUE TITLE
Slow browser

### ISSUE THREAD

**Issue by fabriziodicandia** [luckyrat/KeeFox#651] opened 2016-04-09 17:00 UTC
After having installed KeeFox my browser become quite slow.. I read that other people had this kind of issue, especially with large databases (like mine, with more than 130 entries). I don't know which info might be useful to understand the problem, so AMA so I can help more!

EDIT: I think it might be useful to note my current addons: NoScript, uBlock Origin, HTTPS Everywhere and Chrome Store Foxified. I also have the LastPass addon, but I disabled it while trying KeeFox. (If you are wondering: yes, it works fine, it just seems to have slowed down a lot my browser experience.)

**Comment by dlech** [comment] 2016-04-09 17:44
Duplicate of #563?

**Comment by fabriziodicandia** [comment] 2016-04-09 19:37
mmh yeah it seems so. Should I close this issue and copy/paste my post under #563?

**Comment by dlech** [comment] 2016-04-09 19:58
Yes, that would be helpful.

**Closed** 2016-04-09 20:06 UTC
