### ISSUE TITLE
Keefox not working on thunderbird 45

### ISSUE THREAD

**Issue by sgparry** [luckyrat/KeeFox#679] opened 2016-07-03 13:29 UTC
Been trying to get a clean install of thunderbird working with KeeFox on Windows 10 - the drop down for password choice never appears. Workaround please anybody?

**Comment by dlech** [comment] 2016-07-03 14:11
Duplicate of #656?

**Comment by ntnsndr** [comment] 2016-07-19 22:06
I'm having the same problem. And yes, it appears that #656 is another symptom of the same problem.

**Closed** 2016-11-23 18:49 UTC
Labels: duplicate
