### ISSUE TITLE
Pastes / overwrites info in form fields

### ISSUE THREAD

**Issue by padraic7a** [luckyrat/KeeFox#200] opened 2013-10-02 09:07 UTC
Hi,

when editing my profile on Mozilla Addons (https://addons.mozilla.org) a number of extra form fields are filled by Keefox. 

Please see image attached for example.

![screengrab](https://f.cloud.github.com/assets/3010391/1252133/ccd09238-2b41-11e3-8ac7-e02d6bc0e930.png)

**Comment by luckyrat** [comment] 2015-04-22 15:35
The KEEFOX_CHECKED_FLAG* bug is fixed in KeeFox 1.5.

The Google account problem is not related to this one (and has been discussed at length in the support forums).

I am sure that KeeFox has not changed any level of "aggression" in this respect at any time in the past. Changing behaviour on specific sites is to be expected over a long period of time but there's been no systemic change.

As for the wider issue, there is the usual way to address it: adjust alternative URLs and/or auto-fill settings.

There are some other things a form filler like KeeFox can do to reduce the impact of this class of problem but it's impossible to eliminate it entirely.

#259 has discussion about some possibilities so please follow up there if you want. It's not strictly a duplicate of this issue but if it doesn't quite meet the broader goal of this issue, I'd like to start with a fresh issue with a more targeted an achievable goal.

**Closed by luckyrat** 2015-04-22 15:35 UTC
